# # migration Target --- currently migrations are part of DB Service
# # but maybe it would make more sense to have them in the backend service
FROM postgres:16 AS db_migrate

COPY ./migrations /migrations

RUN apt-get update && apt-get install -y bash

ENTRYPOINT ["bash", "/migrations/migrate.sh"]
